// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1zOGvzoAsVHewlRIslp16Jq5P3tnFa-I',
    appId: '1:148217355085:ios:b2531b4861629895d33504',
    messagingSenderId: '148217355085',
    projectId: 'fir-authpet',
    storageBucket: 'fir-authpet.firebasestorage.app',
    iosBundleId: 'com.example.helloworld',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1zOGvzoAsVHewlRIslp16Jq5P3tnFa-I',
    appId: '1:148217355085:ios:b2531b4861629895d33504',
    messagingSenderId: '148217355085',
    projectId: 'fir-authpet',
    storageBucket: 'fir-authpet.firebasestorage.app',
    iosBundleId: 'com.example.helloworld',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLD5ASAA26u8kf-Q2Q1RxOQw3x86kBrSQ',
    appId: '1:148217355085:web:cc8b3d17500f47abd33504',
    messagingSenderId: '148217355085',
    projectId: 'fir-authpet',
    authDomain: 'fir-authpet.firebaseapp.com',
    storageBucket: 'fir-authpet.firebasestorage.app',
    measurementId: 'G-VZ21Y9XTXQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS7Ijf8UW67xquipgLXgOGZ8_gC01fsOM',
    appId: '1:148217355085:android:40f118ba63cc5e42d33504',
    messagingSenderId: '148217355085',
    projectId: 'fir-authpet',
    storageBucket: 'fir-authpet.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLD5ASAA26u8kf-Q2Q1RxOQw3x86kBrSQ',
    appId: '1:148217355085:web:9213030f4612ce88d33504',
    messagingSenderId: '148217355085',
    projectId: 'fir-authpet',
    authDomain: 'fir-authpet.firebaseapp.com',
    storageBucket: 'fir-authpet.firebasestorage.app',
    measurementId: 'G-WVN436CGQ8',
  );

}